backend:
  name: github
  repo: yessser/web
  branch: "18.0"
  open_authoring: true
publish_mode: editorial_workflow

media_folder: "static/description"
public_folder: "/static/description"

collections:
  - name: "modules"
    label: "Modules"
    label_singular: "Module File"
    folder: "."
    extension: "md"
    format: "raw"
    create: false
    nested:
      depth: 3
    # Media is stored in <module>/static/img/
    media_folder: "{{dirname}}/../static/img"
    # Images are referenced in markdown as ../static/img/image.png
    public_folder: "../static/img"
    summary: "{{filename}}"
    view_groups:
      - label: "Module"
        field: "dirname"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}
