backend:
  name: github
  repo: yessser/web
  branch: "18.0"
  open_authoring: true
publish_mode: editorial_workflow

media_folder: "static/description"
public_folder: "/static/description"

collections:
  - name: "modules"
    label: "Modules"
    label_singular: "Module File"
    folder: "/"
    filter: { field: "path", value: "^[^/]+/readme/.*\\.md$" }
    extension: "md"
    create: false
    nested:
      depth: 3
    summary: "{{filename}}"
    # Media is stored in <module>/static/img/
    media_folder: "{{dirname}}/../static/img"
    # Images are referenced in markdown as ../static/img/image.png
    public_folder: "../static/img"
    identifier_field: "title"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

